### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by 1technophile**
BlueOAk License as proposed by HelpFulEngineering and discussed during project meeting on 03/28 with the team

### CODE REVIEW

**Comment by 1technophile** [comment]
Hi, I'm asking myself if we should move it to firmware folder instead?

**Review by 0x2b3bfa0 — CHANGES_REQUESTED** [review]
As per the [official licensing recommendations](https://helpfulengineering.slack.com/archives/C010GJ68R1N/p1584974903050100), we should be using [CERN-OHL-P](https://ohwr.org/project/cernohl/wikis/Documents/CERN-OHL-version-2), and not [Blue Oak License 1.0.0](https://blueoakcouncil.org/license/1.0.0).

Addressing your original question: no, we should not move the license into any subfolder unless we have multiple licenses.

> **Hardware Projects**
> Everything needed or used to design, make, test or prepare the Medical Hardware or other Contributions  to be made or distributed whether hardware designs, software, schematics or anything else is licensed under the CERN 2.0 Permissive licence (CERN-OHL-P).
> That **includes both firmware and any software that normally comes with the hardware** or other item as well as software used to test it. We recommend placing a TXT file **in the root of the repository**, by the repository owner, with this license in it.

**Review by 0x2b3bfa0 — APPROVED** [review]

**Comment by 0x2b3bfa0** [comment]
@1technophile, feel free to review the changes and merge the pull request if appropriate.

**Comment by 1technophile** [comment]
Thanks for pointing this out, @cavedave are you agree to use the CERN License?

**Comment by cavedave** [comment]
Yes I approve of the CERN license @1technophile @0x2b3bfa0 I should have done this earlier. We gave people enough time to speak up on licenses.

**Pull request merged**
